### ISSUE TITLE
Nextcloud mark down editor deprecated

### ISSUE THREAD

**Issue by lodewiges** [csvalpha/amber-api#430]
![image](https://github.com/user-attachments/assets/d9965762-9476-4f63-a74e-7bbefbe251d1)

Mark down editor is deprecated. i am not sure if we use this if so we need to look for an alternative

**Comment by wilco375** [comment]
https://github.com/icewind1991/files_markdown/issues/218
Compatibility has been an open issue since December 2023 so is not likely to come. It would be nice to have a md editor but if none is available then so be it. We could try another plugin such as https://apps.nextcloud.com/apps/hedgenext (not tested)

**Comment by lodewiges** [comment]
Nextcloud has build in functionality for making markdown files, I looked for maintained alternatives and was unable to find one. due to it not being crucial functionality, I will be closing this issue.
